### ISSUE TITLE
WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'. It will be removed at the end of 2019.

### ISSUE THREAD

**Issue by DwayneZhang** [ITGungnir/KotlinWanAndroid#2]
项目clone之后，报了了这个警告，
WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
API弃用了，但是我全局搜索，没查到哪里调用。
AS Version：3.4.1

**Comment by ITGungnir** [comment]
您好，这个问题是Kotlin的Android插件与Gradle 5.1.1不兼容的现象，让我们一起期待它们的下一个版本吧~~

参考：https://github.com/gradle/gradle/issues/9187
