### ISSUE TITLE
版本更新问题

### ISSUE THREAD

**Issue by fuxiaoyuandroid** [ITGungnir/KotlinWanAndroid#3]
你好，我在Android4.4的手机上点击确定，更新不了，直接崩溃。

**Comment by ITGungnir** [comment]
你好，感谢反馈！问题原因已锁定，将在下个版本解决~

**Comment by fuxiaoyuandroid** [comment]
向你学习




------------------ 原始邮件 ------------------
发件人: "ITGungnir"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 上午10:44
收件人: "ITGungnir/KotlinWanAndroid"<KotlinWanAndroid@noreply.github.com>;
抄送: "付晓宇"<837085046@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ITGungnir/KotlinWanAndroid] 版本更新问题 (#3)




你好，感谢反馈！问题原因已锁定，将在下个版本解决~

**Comment by ITGungnir** [comment]
您好，`V1.2.1`版本已经发布，您可以再测试一下！

（4.4的手机上要卸载后扫码重新下载哦~~）

**Comment by fuxiaoyuandroid** [comment]
好的，谢谢






------------------ 原始邮件 ------------------
发件人: "ITGungnir"<notifications@github.com>;
发送时间: 2019年6月3日(星期一) 中午11:30
收件人: "ITGungnir/KotlinWanAndroid"<KotlinWanAndroid@noreply.github.com>;
抄送: "付晓宇"<837085046@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ITGungnir/KotlinWanAndroid] 版本更新问题 (#3)




您好，V1.2.1版本已经发布，您可以再测试一下！
 
（4.4的手机上要卸载后扫码重新下载哦~~）

**Comment by fuxiaoyuandroid** [comment]
hello，download  unsuccessful,still android 4.4 HongMi Note






------------------ 原始邮件 ------------------
发件人: "ITGungnir"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 中午11:05
收件人: "ITGungnir/KotlinWanAndroid"<KotlinWanAndroid@noreply.github.com>;
抄送: "付晓宇"<837085046@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ITGungnir/KotlinWanAndroid] 版本更新问题 (#3)




Closed #3.
