### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by SmallerRiver** [ITGungnir/KotlinWanAndroid#4]
BaseRedux里面的middlewareList的意义是什么 而且在apply方法里面的使用基本是直接返回了Action   能回答一下思路吗

**Comment by HelloVass** [comment]
[Redux](https://redux.js.org/) 这个库是来自前端 React Redux 的移动端实现，核心就是单向数据流。而 middleware 是啥，其实就是副作用，例如从服务端获取数据、从数据库获取数据等等，说白了就是理想是只有同步 Action，但是真实世界副作用不可避免，所以，我们需要 middleware 将异步 action 转为同步。

这个库作者直接返回了 Action，是因为，这个版本的 Redux 并没有对 middleware 做很好的支持，副作用是开发者自己处理的，处理过后的 action 可以理解为是同步的了，就直接 dispatch 了。

**Comment by HelloVass** [comment]
@SmallerRiver
 [Redux](https://redux.js.org/) 这个库是来自前端 React Redux 的移动端实现，核心就是单向数据流。而 middleware 是啥，其实就是副作用，例如从服务端获取数据、从数据库获取数据等等，说白了就是理想是只有同步 Action，但是真实世界副作用不可避免，所以，我们需要 middleware 将异步 action 转为同步。

这个库作者直接返回了 Action，是因为，这个版本的 Redux 并没有对 middleware 做很好的支持，副作用是开发者自己处理的，处理过后的 action 可以理解为是同步的了，就直接 dispatch 了。

**Comment by SmallerRiver** [comment]
> @SmallerRiver
> [Redux](https://redux.js.org/) 这个库是来自前端 React Redux 的移动端实现，核心就是单向数据流。而 middleware 是啥，其实就是副作用，例如从服务端获取数据、从数据库获取数据等等，说白了就是理想是只有同步 Action，但是真实世界副作用不可避免，所以，我们需要 middleware 将异步 action 转为同步。
> 
> 这个库作者直接返回了 Action，是因为，这个版本的 Redux 并没有对 middleware 做很好的支持，副作用是开发者自己处理的，处理过后的 action 可以理解为是同步的了，就直接 dispatch 了。

明白了 谢谢
