### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by ouyuan2019** [ITGungnir/KotlinWanAndroid#6]
看代码好像并没有RxJava销毁的代码，不会内存泄漏吗？

**Comment by ITGungnir** [comment]
不会的，因为我使用了LiveData来管理从网络中请求到的数据。

具体的做法是：在ViewModel中进行网络请求，然后将数据存储到LiveData中；Activity或Fragment中监听LiveData中的数据，当数据发生变化时更新UI。

LiveData仅会在所绑定的生命周期组件（Activity或Fragment）为激活（active）状态下才会进行数据响应，当Activity或Fragment被销毁之后，将不会再收到数据。

通过这种方式实现了V层和M层的解耦，因此不会发生内存泄漏。
